name: nia_ksl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - argh=0.26.2
  - astroid=2.4.2
  - async_generator=1.10
  - atomicwrites=1.4.0
  - autopep8=1.5.4
  - babel=2.8.0
  - backcall=0.2.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - chardet=3.0.4
  - cloudpickle=1.6.0
  - cudatoolkit=10.1.243
  - cudnn=7.6.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.10
  - flake8=3.8.4
  - fontconfig=2.13.0
  - freetype=2.10.4
  - future=0.18.2
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - imagesize=1.2.0
  - importlib_metadata=2.0.0
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - isort=5.6.4
  - jedi=0.17.1
  - jeepney=0.4.3
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - keyring=21.4.0
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - numpydoc=1.1.0
  - openssl=1.1.1h
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pathtools=0.1.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.4
  - pluggy=0.13.1
  - prompt-toolkit=3.0.8
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - pycodestyle=2.6.0
  - pydocstyle=5.1.1
  - pyflakes=2.2.0
  - pygments=2.7.1
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - pyxdg=0.26
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=1.0.1
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - rope=0.18.0
  - rtree=0.9.4
  - secretstorage=3.1.2
  - setuptools=50.3.0
  - sip=4.19.13
  - snowballstemmer=2.0.0
  - sortedcontainers=2.2.2
  - sphinx=3.2.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.1.5
  - spyder-kernels=1.9.4
  - sqlite=3.33.0
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - traitlets=5.0.5
  - ujson=4.0.1
  - watchdog=0.10.3
  - webencodings=0.5.1
  - wheel=0.35.1
  - wrapt=1.11.2
  - wurlitzer=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.3
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - asn1crypto==1.2.0
    - astor==0.8.1
    - astunparse==1.6.3
    - attrs==19.3.0
    - blessings==1.7
    - cachetools==4.0.0
    - certifi==2019.11.28
    - cffi==1.13.2
    - cryptography==2.8
    - cycler==0.10.0
    - fvcore==0.1.2.post20201020
    - gast==0.2.2
    - google-auth==1.10.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - gpustat==0.6.0
    - grpcio==1.26.0
    - h5py==2.10.0
    - idna==2.8
    - importlib-metadata==1.5.0
    - jamotools==0.1.10
    - joblib==0.14.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - keyboard==0.13.5
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - matplotlib==3.1.2
    - more-itertools==8.2.0
    - natsort==7.0.1
    - numpy==1.18.1
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencv-python==4.2.0.32
    - opt-einsum==3.1.0
    - packaging==20.3
    - pandas==1.0.3
    - pillow==7.1.0
    - plotly==4.5.0
    - portalocker==1.5.2
    - protobuf==3.11.2
    - py==1.8.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycosat==0.6.3
    - pycparser==2.19
    - pyparsing==2.4.6
    - pytest==5.4.0
    - pytz==2019.3
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.0
    - ruamel-yaml==0.15.87
    - sacrebleu==1.4.4
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - sentencepiece==0.1.85
    - six==1.13.0
    - tabulate==0.8.7
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - tensorflow-hub==0.9.0
    - termcolor==1.1.0
    - tflearn==0.3.2
    - torch==1.4.0
    - torchtext==0.5.0
    - torchvision==0.5.0
    - tqdm==4.40.2
    - typing==3.7.4.1
    - urllib3==1.25.7
    - wcwidth==0.1.8
    - werkzeug==0.16.0
    - xmltodict==0.12.0
    - yacs==0.1.8
    - zipp==3.1.0

